name: portfolio_yacine
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  animated_text_kit: ^4.2.2
  url_launcher: ^6.3.0
  path_provider: ^2.1.4
  open_file: ^3.3.0
  another_flutter_splash_screen: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

  flutter_launcher_icons: ^0.13.1
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/cv.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/images/cv.png"
  windows:
    generate: true
    image_path: "assets/images/cv.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/images/cv.png"

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
